project_id = "academy"

[api]
enabled = true
port = 54322
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54323
shadow_port = 54324
major_version = 15

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[edge_runtime]
enabled = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.reconcile-payments]
verify_jwt = false

[functions.course-deposit-webhook]
verify_jwt = false

[functions.reconcile-course-payments]
verify_jwt = false
